name: tests

on:
  push:
    paths-ignore:
      - "docs/**"
      - "*.md"
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install poetry
          cd D:\a\Categorize-CLI
          .venv\Scripts\activate
          python3 -m pip install -r requirements.txt
          python3 -m pip install -e .
          poetry run python -m pip install -U pip setuptools
      - name: Test with pytest
        run: |
          poetry run pytest